### ISSUE TITLE
adjust the design

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/blockex#7]
https://app.zeplin.io/project/5c2f74222481d659f53bdb85?seid=5c5840eda25e8f427ff58900

**Comment by gingervik** [comment]
![image](https://user-images.githubusercontent.com/28015224/53408025-92c5e600-39ce-11e9-8cef-76551313f04d.png)

1. size of switching button (should be 288x31 instead of 288x33)
2. Hash rate switcher should be alligned with mainnet/testnet switcher
3. fee chart and info blocks should be alligned with search by element
4. Y axis labels should be alligned with mainnet/testnet switcher
5. Align beam icon and name
6.  blocks and difficulty chart should be moved to the left

**Comment by Sergei-Beam** [comment]
7.  Change the graph legend on tooltip from circle to line
![image](https://user-images.githubusercontent.com/44496108/53552976-a186d700-3b4d-11e9-939c-1f2f61e31b44.png)
8. Change font according to design
![image](https://user-images.githubusercontent.com/44496108/53553017-b8c5c480-3b4d-11e9-9332-88edf2682143.png)

**Comment by Sergei-Beam** [comment]
8 related to 7
 Graph's legend line has a different thickness on different points of the graph
![graph](https://user-images.githubusercontent.com/44496108/53885553-1a46d100-402f-11e9-8edd-4920fec7394b.gif)
9. Align Graph's names and Period dropdown
![image](https://user-images.githubusercontent.com/44496108/53884948-aeb03400-402d-11e9-9878-5ec834c9494f.png)
10. Align block's table according to design
![image](https://user-images.githubusercontent.com/44496108/53885431-bd4b1b00-402e-11e9-8304-6843d544ccff.png)

**Comment by Sergei-Beam** [comment]
checked
